{
 "title": "bank-rs",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Количество предсказаний продуктов",
   "type": "bargauge",
   "gridPos": { "h": 21, "w": 14, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "summarize(stats.bank-rs.target.*, '15min', 'sum')"
    }
   ]
  },
  {
   "title": "Время отклика",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "target": "stats.timers.bank-rs.response_time.mean_90"
    }
   ]
  },
  {
   "title": "Динамика успешных (200) запросов",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 14, "y": 6 },
   "targets": [
    {
     "target": "movingAverage(stats.bank-rs.response_code.200, '10min')"
    }
   ]
  },
  {
   "title": "Загрузка CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "stats.gauges.bank-rs.bank-rs.system.cpu_load"
    }
   ]
  },
  {
   "title": "Свободная память",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.bank-rs.bank-rs.system.memory_free_mb"
    }
   ]
  },
  {
   "title": "Запросов за период",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "target": "stats.bank-rs.bank-rs.requests" }
   ]
  },
  {
   "title": "Время работы",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "dthms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "stats.gauges.bank-rs.bank-rs.system.up_time"
    }
   ]
  }
 ]
}